DELETE http://localhost:3003/api/blogs/60ffd7ae50a1c1408c279209
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3Rpa8OkeXR0w6Rqw6QiLCJpZCI6IjYwZmU4MzQ4MGNiMjMzNTExOGI1NmNlMyIsImlhdCI6MTYyNzM3ODA1MX0.b9h3xjqYoK-g1GFcqHIBnJ2R7VrRbgvbUSiHWz4LVd4