POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxMTRjZjNkNGRiYThmMzAxMGRmMDZjMiIsImlhdCI6MTYyODg0NTM2MX0.i1xJU-00ir1WpyxviANl07TqDI_SdchzqEy8CJwPQQE

{
  "title": "Commented blog2",
  "author": "Testi blogin kirjoittaja",
  "url": "BlogURL.org",
  "likes": 10,
  "user": "60fe83480cb2335118b56ce3",
  "comments": [
    "Awesome stuff",
    "Work of the master of the universe"
  ]
}